---
title: "TODOs"
author: "Peter Hickey"
date: "`r paste0('Modified: 09 October, 2014. Compiled: ', format(Sys.time(), '%d %B, %Y'))`"
output:
  BiocStyle::pdf_document
---

<!--
%% \VignetteEngine{knitr::knitr}
-->

```{r style, echo = FALSE, results = 'asis'}
BiocStyle::markdown()
```

# Functions to write

- [ ] `strandCollapse`: To collapse a `MethPat` object by strand. Only 
applicable when methylation type is `CG`.

# Variable_naming.Scheme

Get some bloody consistency! 


# For submission to \Bioconductor{}

These are issues that must be addressed either before or during the 
\Bioconductor{} submission process.

## Package name

I'm concerned the `r Rpackage("MethylationTuples")` name might be a bit long 
and clumsy.

I need to settle on a package name. `r Rpackage("MethylationTuples")` mimics 
the `r Githubpkg("PeteHaitch/GenomicTuples")` that it depends upon. It is also 
similar to \software{methtuple}, whose output files this package reads in and 
works with.

On a minor note: that \software{methtuple} is singular, whereas both 
`r Githubpkg("PeteHaitch/GenomicTuples")` and `r Rpackage("MethylationTuples")` 
are plural, grates on me.

Possible alternatives:  `r Rpackage("MethTuples")`, other? Can't use 
`r Rpackage("MethPat")` as this is already being used.

## Dependencies

The package will require `BSgenome`, but at this stage I'm not sure whether it 
should be in DEPENDS or IMPORTS. Various `BSgenome`-organism packages should be 
listed in SUGGESTS.