// This file was automatically generated by 'Kmisc::registerFunctions()'

#include <R.h>
#include <Rinternals.h>

#include <R_ext/Rdynload.h>

SEXP MethylationTuples_makeAllPairs(SEXP sSEXP, SEXP max_ipdSEXP);

R_CallMethodDef callMethods[]  = {
  {"Cpp_MethylationTuples_makeAllPairs", (DL_FUNC) &MethylationTuples_makeAllPairs, 2},
  {NULL, NULL, 0}
};

void R_init_MethylationTuples(DllInfo *info) {
  R_registerRoutines(info, NULL, callMethods, NULL, NULL);
  R_useDynamicSymbols(info, FALSE);
}

