// This file was automatically generated by 'Kmisc::registerFunctions()'

#include <R.h>
#include <Rinternals.h>

#include <R_ext/Rdynload.h>

SEXP MethylationTuples_makeAdjacentPairs(SEXP methpat_orderSEXP, SEXP seqnamesSEXP, SEXP strandSEXP, SEXP posSEXP, SEXP feature_statusSEXP, SEXP betasSEXP, SEXP id_dtSEXP);
SEXP MethylationTuples_makeAllPairs(SEXP methpat_orderSEXP, SEXP seqnamesSEXP, SEXP strandSEXP, SEXP posSEXP, SEXP feature_statusSEXP, SEXP ipdSEXP, SEXP betasSEXP, SEXP id_dtSEXP);

R_CallMethodDef callMethods[]  = {
  {"Cpp_MethylationTuples_makeAdjacentPairs", (DL_FUNC) &MethylationTuples_makeAdjacentPairs, 7},
  {"Cpp_MethylationTuples_makeAllPairs", (DL_FUNC) &MethylationTuples_makeAllPairs, 8},
  {NULL, NULL, 0}
};

void R_init_MethylationTuples(DllInfo *info) {
  R_registerRoutines(info, NULL, callMethods, NULL, NULL);
  R_useDynamicSymbols(info, FALSE);
}

