# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create all pairs of beta-values within a given IPD.
#' 
#' In the description below, \code{x} is a \code{\link{MethPat}} object 
#' containing 1-tuples. The argument descriptions are chosen for clarity, not 
#' because they are necessarily an efficient way to obtain said arguments.
#' 
#' @param methpat_order \code{order(x)}.
#' @param seqnames \code{as.character(seqnames(sort(x)))}.
#' @param strand \code{as.character(sort(x))}.
#' @param pos \code{start(sort(x))}.
#' @param feature_status \code{overlapsAny(x, feature)}.
#' @param ipd An integer vector of IPD, e.g., \code{ipd = 1:100}.
#' @param betas \code{betaVal(x)}
#' @param id_dt A \code{\link[data.table]{data.table}} mapping the
#' seqnames-strand-feature_status combination to an integer ID.
makeAllPairsCpp <- function(methpat_order, seqnames, strand, pos, feature_status, ipd, betas, id_dt) {
    .Call('MethylationTuples_makeAllPairs', PACKAGE = 'MethylationTuples', methpat_order, seqnames, strand, pos, feature_status, ipd, betas, id_dt)
}

