# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create adjacent pairs of beta-values.
#' 
#' In the description below, \code{x} is a \code{\link{MethPat}} object 
#' containing 1-tuples. The argument descriptions are chosen for clarity, not 
#' because they are necessarily an efficient way to obtain said arguments.
#'
#' @param methpat_order \code{order(x)}.
#' @param seqnames \code{as.character(seqnames(sort(x)))}.
#' @param strand \code{as.character(sort(x))}.
#' @param pos \code{start(sort(x))}.
#' @param in_feature \code{overlapsAny(x, feature)} or \code{rep(NA, nrow(x))} 
#' if no feature is supplied to \code{betaCor}.
#' @param betas \code{betaVal(x)}
#' @param id_dt A \code{\link[data.table]{data.table}} mapping the
#' \code{seqnames-strand-IPD-in_feature} combination to an integer ID.
#' 
#' @keywords internal
#' 
#' @return A \code{list} with the \code{ID}, \code{sample}, \code{beta1} and 
#' \code{beta2} of each pair.
.makeAdjacentPairsCpp <- function(methpat_order, seqnames, strand, pos, in_feature, betas, id_dt) {
    .Call('MethylationTuples_makeAdjacentPairs', PACKAGE = 'MethylationTuples', methpat_order, seqnames, strand, pos, in_feature, betas, id_dt)
}

#' Create all pairs of beta-values with given IPDs.
#' 
#' In the description below, \code{x} is a \code{\link{MethPat}} object 
#' containing 1-tuples. The argument descriptions are chosen for clarity, not 
#' because they are necessarily an efficient way to obtain said arguments.
#' 
#' @param methpat_order \code{order(x)}.
#' @param seqnames \code{as.character(seqnames(sort(x)))}.
#' @param strand \code{as.character(sort(x))}.
#' @param pos \code{start(sort(x))}.
#' @param in_feature \code{overlapsAny(x, feature)} or \code{rep(NA, nrow(x))} 
#' if no feature is supplied to \code{betaCor}.
#' \code{rep(NA_integer_, nrow(x))} if no feature is supplied to 
#' \code{betaCor}.
#' @param ipd An integer vector of IPD, e.g., \code{ipd = 1:100}.
#' @param betas \code{betaVal(x)}
#' @param id_dt A \code{\link[data.table]{data.table}} mapping the
#' \code{seqnames-strand-IPD-in_feature} combination to an integer ID.
#' 
#' @keywords internal
#' 
#' @return A \code{list} with the \code{ID}, \code{sample}, \code{beta1} and 
#' \code{beta2} of each pair.
.makeAllPairsCpp <- function(methpat_order, seqnames, strand, pos, in_feature, ipd, betas, id_dt) {
    .Call('MethylationTuples_makeAllPairs', PACKAGE = 'MethylationTuples', methpat_order, seqnames, strand, pos, in_feature, ipd, betas, id_dt)
}

